#!/usr/bin/env python3
"""Convert Misaki font data from Python tuple format to TypeScript."""

import re

FONT_DATA_PATH = "misakifont/misakifontdata.py"
OUTPUT_PATH = "worker/src/font-misaki.ts"

with open(FONT_DATA_PATH) as f:
    src = f.read()

# Extract misaki_font_data tuple
data_match = re.search(r"misaki_font_data = \(\n(.+?)\n\)", src, re.DOTALL)
table_match = re.search(r"misaki_font_table = \(\n(.+?)\n\)", src, re.DOTALL)

def parse_hex_tuple(text):
    numbers = re.findall(r"0x[0-9a-fA-F]+", text)
    return [int(n, 16) for n in numbers]

font_data = parse_hex_tuple(data_match.group(1))
font_table = parse_hex_tuple(table_match.group(1))

print(f"Font table entries: {len(font_table)}")
print(f"Font data bytes: {len(font_data)}")
print(f"Bytes per glyph: {len(font_data) // len(font_table)}")
print(f"First few table entries: {font_table[:5]}")
print(f"Last few table entries: {font_table[-5:]}")

# Write TypeScript
with open(OUTPUT_PATH, "w") as f:
    f.write("// Auto-generated by convert_font.py — do not edit manually\n")
    f.write("// Misaki 8x8 font (1710 glyphs, 7 bytes each)\n\n")

    # Font table as JS number array
    table_str = ", ".join(f"0x{c:04x}" for c in font_table)
    f.write(f"export const MISAKI_FONT_TABLE: number[] = [{table_str}];\n\n")

    # Font data as Uint8Array
    f.write(f"export const MISAKI_FONT_DATA = new Uint8Array([{', '.join(hex(b) for b in font_data)}]);\n")

print(f"Written to {OUTPUT_PATH}")