name = "epd-display"
main = "src/index.ts"
compatibility_date = "2025-04-18"

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "31ca3f12141048929c5c052419576ec9"

[vars]
WORKER_URL = "https://epd-display.dragon-aka-scooter.workers.dev"
